version: '3.8'

services:

  mysql-db:
    container_name: mysql-db
    image: mysql:8.0.28
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: template-db